# mybatis配置文件以及映射文件配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:order/mappers/*.xml
# 服务器相关配置
server:
  address: localhost
  port: 9090
  servlet:
    context-path: /elastic-job-order
# spring相关配置
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver       # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/elasticjob_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai         # 数据库连接地址
    username: root                                  # 数据库用户名
    password: mysql                                 # 数据库连接密码
    # 配置当前要使用的数据源的操作类型
    druid:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-active: 5                                 # 最大的连接数
      max-wait: 200                                 # 等待连接获取的最大超时时间
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
elaticjob:
  zookeeper:
    server-lists: 192.168.199.128:2181
    namespace: order-project